### ISSUE TITLE
Expose clang-format and other tools

### ISSUE THREAD

**Issue by Kernald** [grailbio/bazel-toolchain#11]
Given that some tools like clang-format, clang-tidy... are bundled in the LLVM distribution, it would be nice to expose them.

**Comment by siddharthab** [comment]
Thanks for discussing this. These are currently available directly in the bin directory. For example, `@llvm_toolchain//:bin/clang-tidy`. Will this suffice? I can add documentation for this in the README if you would like.

**Comment by Kernald** [comment]
Awesome, I didn't realise this was already done! A mention in the README would probably make clear that this is by design and not an implementation detail, in addition to making this obvious. It probably wouldn't hurt :-)

**Comment by siddharthab** [comment]
Yeah, no worries. I can mention it in the README that direct access to the bin directory is intentional.

**Comment by siddharthab** [comment]
I added a small note in 2820ccb9638a354ff95a7c7649c90052a00e5ecd.

**Comment by Kernald** [comment]
Perfect, thanks!
