### ISSUE TITLE
Builds fail on old macOS versions that have `libtool` versions w/o arg file support

### ISSUE THREAD

**Issue by rrbutani** [grailbio/bazel-toolchain#114]
We use `libtool` instead of `llvm-ar` on macOS [because](https://github.com/grailbio/bazel-toolchain/blob/e96102391767edddba3923f3a6861aca1581b5a9/toolchain/cc_toolchain_config.bzl#L239) the commands that Bazel generates on macOS hosts don't work with `llvm-ar`.

I don't know when support for arg files (i.e. `libtool @arg-file`) was added to macOS's `libtool` but at the very least macOS 10.12's `libtool` (`cctools-900`) does not support this.

Bazel's native `rules_cc` machinery does not seem to pick up on this so builds fail on such machines at the archiving step.

**Comment by siddharthab** [comment]
Just curious. Where is macOS 10.12 being used? Its last security update was 2 years ago.

**Comment by rrbutani** [comment]
Oh sorry, I probably should have mentioned; this is just an old machine that I have. I think it's completely valid to decide that this isn't something `bazel-toolchain` will support.

----

Looking through the releases [here](https://opensource.apple.com/source/cctools/), it looks like [`949.0.1` is the oldest listed release](https://opensource.apple.com/source/cctools/cctools-949.0.1/misc/libtool.c.auto.html) with arg file support which I think isn't that old (a couple of years or so). I'm not sure how cctools versions map to macOS releases.

**Comment by siddharthab** [comment]
It's alright. And the PR you sent also looks OK.

I think in general, we should not invite structural/organizational complexity into the codebase to support older releases of stuff. This project is pre-release, and its intended target audience would usually stay current with releases. I generally prefer code simplicity over supporting a very minor use case.

I think it is OK to drop support for:
1. old versions of LLVM, say more than 3 or 4 versions behind the current release.
2. Linux and macOS versions that are past their end-of-life.
3. [non-LTS releases](https://blog.bazel.build/2020/11/10/long-term-support-release.html) of bazel.
