### ISSUE TITLE
Support for s390x (-march=systemz) platform

### ISSUE THREAD

**Issue by udai05** [grailbio/bazel-toolchain#122]
Looking for steps to add support for s390x platform. 
I am trying to build prysm using bazel but I see am seeing build failing due llvm_toolchain dependency.

**Comment by rrbutani** [comment]
At the moment, I think [this commit](https://github.com/grailbio/bazel-toolchain/commit/85022a2dc9537827963bb43319a437a9bb70a97f) is probably the best reference for how to add support for another host platform.

I think the best place to start would be adding support for actually fetching the toolchain (`llvm_distributions.bzl`, `llvm_release_name.py`) however, as far as I can tell, there aren't official LLVM releases for s390x.

Just to be clear: are you looking to compile for s390x from an s390x or are you looking to cross compile?

**Comment by US-05** [comment]
Thanks @rrbutani for the quick reply.  
I am using s390x machine to build for the same platform. I am novice to Bazel, hence this query. 

Say after I've added support for s390x (i.e., build goes through after couple of tries), how do I point Prysm bazel WORKSPACE to local llvm_toolchain?

**Comment by rrbutani** [comment]
> I am using s390x machine to build for the same platform.

Got it. I think the fact that there aren't official LLVM releases for s390x will make it hard for us to add proper support for s390x to this repo (we could maybe use and extract the binaries from [the `.dpkg`s](https://apt.llvm.org/) for s390x for the debian based distros we support?) but you can certainly add the logic for s390x hosts/targets and punt on the "getting the toolchain" bit for now. I think we'd be happy to accept a PR that does this; not figuring out how/where to get the toolchain shouldn't be a blocker.

> Say after I've added support for s390x (i.e., build goes through after couple of tries), how do I point Prysm bazel WORKSPACE to local llvm_toolchain?

You'll need to update the Prysm `WORKSPACE` to point to your modified version of `bazel-toolchain` (i.e. probably sub [this](https://github.com/prysmaticlabs/prysm/blob/d78428c49e2165df8065c362a94288058d66d0e1/WORKSPACE#L16-L20) for a `local_repository` while you're testing).

Besides that you should just be able to use `toolchain_roots` in the `llvm_toolchain` macro to point to your local LLVM install (see [this](https://github.com/grailbio/bazel-toolchain#bring-your-own-llvm) and [this](https://github.com/grailbio/bazel-toolchain/blob/a912bb381b36437be0eeb22de11f0ea198450b4e/toolchain/rules.bzl#L84-L96); something like `toolchain_roots = { "": "/usr/" }` should work).

**Comment by udai05** [comment]
@rrbutani I was away for a while.
Meanwhile, I did compile llvm-project for s390x. 
```
us@bd-zvsi:~/tools/llvm-project/build/bin$ ./clang-14 --version
clang version 14.0.0 (https://github.com/llvm/llvm-project.git bde561c4813952847112600e5efe72d9015556f7)
Target: s390x-ibm-linux
Thread model: posix
InstalledDir: /data/us/tools/llvm-project/build/bin/.
```
>You'll need to update the Prysm WORKSPACE to point to your modified version of bazel-toolchain (i.e. probably sub this for a local_repository while you're testing). 

Could you help me with WORKSPACE related changes. 

> Besides that you should just be able to use ```toolchain_roots``` in the ``llvm_toolchain``` macro to point to your local LLVM install (see this and this; something like ```toolchain_roots = { "": "/usr/" }``` should work).

I can move ```/data/us/tools/llvm-project/build/``` to ```/usr/local/``` so that the above rules holds true.

**Comment by siddharthab** [comment]
I have now added a README section for this -- https://github.com/grailbio/bazel-toolchain/blob/master/README.md#supporting-new-target-platforms.

I am going to close this issue now, but please feel free to reopen the issue in case things don't work out.
