### ISSUE TITLE
bzlmod support

### ISSUE THREAD

**Issue by jsharpe** [grailbio/bazel-toolchain#128]
Create bzlmod module extensions and submit an entry to https://github.com/bazelbuild/bazel-central-registry

**Comment by siddharthab** [comment]
Opened https://github.com/bazelbuild/bazel-central-registry/pull/923.

**Comment by siddharthab** [comment]
So sorry I did not notice it in the review. What's the best way to forward all the attributes rather than copy/pasting?

**Comment by jsharpe** [comment]
I'm not exactly sure; there are a lot of attributes that need to be forwarded but so you would want to do the equivalent of `(**tag_class.attrs)` on the call to the rule. I'm not sure if that works though? Can give it a try..

**Comment by siddharthab** [comment]
Resolved by #218. When you are done testing, I can cut a new patch release.

**Comment by siddharthab** [comment]
Also please feel free to send PRs as you are testing. Will make the whole process much easier. I no longer use this project in any major codebase, so the unit tests here are the only things I run.

**Comment by jlisee** [comment]
The [release notes for 0.10.2](https://github.com/grailbio/bazel-toolchain/releases/tag/0.10.2) have instructions on how to use  Bzlmod but how do we do that if https://github.com/bazelbuild/bazel-central-registry/pull/923 has not yet landed in the central registry?

From looking at your commit history you have an override like this, do still need something similar:
```
git_override(module_name = "com_grail_bazel_toolchain", remote = "https://github.com/grailbio/bazel-toolchain", commit = "cf915e5c7cfcd19a3e71de54e385e01240b865dc")
```

**Comment by siddharthab** [comment]
Yes, I had hoped that the inclusion into BCR would be quick but it has taken some time. `git_override` would be a good way to do this. You can keep the module_name to be "toolchains_llvm". I will add this detail to the release notes.

**Comment by siddharthab** [comment]
https://github.com/grailbio/bazel-toolchain/releases/tag/0.10.3
