### ISSUE TITLE
Add support for mold linker

### ISSUE THREAD

**Issue by jsharpe** [grailbio/bazel-toolchain#132]
See: https://github.com/rui314/mold

mold provides a wrapper that injects itself into the compile so this could be done by updating the compiler wrapper to include a call to mold.

**Comment by siddharthab** [comment]
See #137 for examples on how to pick up `mold` from the host.

We could work on a mechanism to incorporate arbitrary tools (mostly linkers I think) into the toolchain, by placing them in the bin directory or editing the PATH variable, but I think that can be a separate issue. For the time being, if the user is really motivated, they could create their own archives which would include mold in them.

I am closing this now, but please feel free to reopen if the original issue is not addressed.
