### ISSUE TITLE
Plain "python" is not available on many modern distributions

### ISSUE THREAD

**Issue by refi64** [grailbio/bazel-toolchain#14]
Out-of-the-box, most distros are shipping Python 3 nowadays, which means that no "python" binary is available without installing Python 2.

**Comment by siddharthab** [comment]
Thank you for the report. Can you give me a few examples of such distros?

My understanding is that while [PEP 394](https://www.python.org/dev/peps/pep-0394/) is active, OS distros should continue to include a `python` command.

**Comment by refi64** [comment]
The gotcha is here: 
> for the time being, all distributions should ensure that python, **if installed**, refers to the same target as python2

Since Python 2 is reaching EOL next year, many distros already don't have it installed by default, and others are trying to begin to drop it altogether.

In particular, both Fedora and RHEL 8 use Python 3 by default.

**Comment by siddharthab** [comment]
Understood. I will update the shebang line after testing with our supported OS distros.
