### ISSUE TITLE
do we support sanitizers?

### ISSUE THREAD

**Issue by luxe** [grailbio/bazel-toolchain#15]
I'm trying to build with a sanitizer turned on:
```
bazel build //code:foo --crosstool_top=@llvm_toolchain//:toolchain --copt=-fsanitize=undefined
```
However, it fails to link:
```
...
ld.lld: error: undefined symbol: __ubsan_handle_type_mismatch_v1
...
```

I think I need to use a linker that's not `lld`?
Clang docs say:  

> Make sure to use clang++ (not ld) as a linker, so that your executable is linked with proper UBSan runtime libraries.

I'm trying to figure out how do to this?  
Do you think I can overwrite what is getting set in `cc_toolchain_config.bzl.tpl`?

**Comment by luxe** [comment]
I tried getting rid of `"-fuse-ld=lld",` in the config, but it didn't work.  I suppose its unrelated to using lld.

**Comment by siddharthab** [comment]
Can you try repeating the option for both copt and linkopt. Example -- https://abseil.io/docs/cpp/guides/base#leak-checking

This is because copt flags do not get passed down to the linking step. You need to specify them separately.

**Comment by luxe** [comment]
you're exactly right
`--copt=-fsanitize=address --linkopt=-fsanitize=address`.  
thanks a ton!
