### ISSUE TITLE
Questions about the toolchain

### ISSUE THREAD

**Issue by Oran-Ac** [grailbio/bazel-toolchain#161]
Hi thanks so much for your work. I am not that familiar with `Bazel` as well as `llvm`. I wonder whether it can be used to get the llvm IR while using `bezel` to build the project, e.g., `tensorflow`. If so, how can we do that? Many thanks.

**Comment by siddharthab** [comment]
This is out of scope for this project. This would need to be supported at the level of the cc_* rules and they are defined within bazel. So unless bazel supports this, it can not be done here. An alternative would be to write alternative C++ rules but that will be a large body of work.
