### ISSUE TITLE
header not found error for X compilation with system llvm

### ISSUE THREAD

**Issue by storypku** [grailbio/bazel-toolchain#165]
## How to reproduce
1. Download and extract llvm release 14.0.0 to, say, `/tmp/llvm-14`
2. change `toolchain_roots` to  default to `/tmp/llvm-14` for `llvm_toolchain_with_sysroot` (in tests/WORKSPACE) 
3. in the `tests` dir, run `scripts/run_xcompile_test.sh`. 

Here is the snapshot of the build failure on my Ubuntu 18.04
![image](https://user-images.githubusercontent.com/1758353/205240392-07c78605-e5ad-4b93-bf14-4e45542a891e.png)

# What's more:
If we add the following sysroot for arm64 (in tests/WORKSPACE)

```
http_archive(
    name = "chromium_sysroot_linux_arm64",
    build_file_content = """
filegroup(
  name = "sysroot",
  srcs = glob(["*/**"]),
  visibility = ["//visibility:public"],
)
""",
    sha256 = "0d4ba53fa4aed14e50c07a65131d078f2a3ee2f53e695ed93855facf4860bea5",
    urls = [
        "https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/1126d9b629c97385a503debac7a1b59e60a3ab1b/debian_stretch_arm64_sysroot.tar.xz",
    ],
)
```

And defines a platform:

```
platform(
    name = "linux-aarch64-cross",
    exec_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
    ],
)
```

Running 
```
/usr/bin/bazel --bazelrc=/dev/null build --incompatible_enable_cc_toolchain_resolution --platforms=@com_grail_bazel_toolchain//platforms:linux-aarch64-cross --extra_toolchains=@llvm_toolchain_with_sysroot//:cc-toolchain-aarch64-linux --symlink_prefix=/ --color=yes //:stdlib_test
```
failed with:

![image](https://user-images.githubusercontent.com/1758353/205241337-d250690f-319f-4924-9285-50296ef67039.png)

**Comment by siddharthab** [comment]
This is a bug. Thanks for reporting. I am not handling paths properly when using absolute paths and sysroots.

**Comment by siddharthab** [comment]
Can you check now please?

**Comment by storypku** [comment]
> Can you check now please?
Great! It works now!
