### ISSUE TITLE
missing dependency errors when building with `--copt -fsanitize=address` with `absolute_paths = True`

### ISSUE THREAD

**Issue by garymm** [grailbio/bazel-toolchain#184]
Whenever I build anything with `--copt -fsanitize=address`, I get errors like:

```
ERROR: /home/garymm/.cache/bazel/_bazel_garymm/3e948c06be790e3e64e6aacacdab772a/external/libpng/BUILD.bazel:22:11: Compiling pngwio.c failed: undeclared inclusion(s) in rule '@libpng//:libpng':
this rule is missing dependency declarations for the following files included by 'pngwio.c':
  '/home/garymm/.cache/bazel/_bazel_garymm/3e948c06be790e3e64e6aacacdab772a/external/llvm_toolchain_llvm/lib/clang/15.0.6/share/asan_ignorelist.txt'
```

Would this be fixed if we add `"lib/clang/{}/share".format(llvm_version),` here?
https://github.com/grailbio/bazel-toolchain/blob/08d1aa8cee67a7a9c51c09225cead1dad42dadc3/toolchain/cc_toolchain_config.bzl#L271

**Comment by siddharthab** [comment]
I don't mind the change you are suggesting. If you send a PR that works for you, I will accept it.

However, I can not reproduce this with the unit tests in this repo. Can you give me a reproducible example please? Can you also try your example with `--copt -fno-sanitize-ignorelist`?

**Comment by siddharthab** [comment]
For example, in the unit tests here:

```
cd tests
bazel build --copt -fsanitize=address --linkopt -fsanitize=address @com_google_absl//...
```

**Comment by garymm** [comment]
Ah it appears this happens only when `absolute_paths = True` is set in `llvm_toolchain()`.

**Comment by siddharthab** [comment]
Thanks for looking into it.
