### ISSUE TITLE
Update llvm to 9.0.0

### ISSUE THREAD

**Issue by mattgodbolt** [grailbio/bazel-toolchain#22]
LLVM 9 is now out: would be great to support it. Thanks!

**Comment by siddharthab** [comment]
I have added the checksums in 15ae8b9ff31686c8fadf84b2742dcf587ec18ec7. But because this release does not include macOS, I have not updated the README and the default version used in the tests.

**Comment by mattgodbolt** [comment]
Thanks so much!
