### ISSUE TITLE
Bazel 1.0.0 compatibility

### ISSUE THREAD

**Issue by sabarabc** [grailbio/bazel-toolchain#25]
Trying to build a project with the latest version of this project and LLVM 9.0.0 on Bazel 1.0.0 gives the following error:

```
src/main/tools/linux-sandbox-pid1.cc:427: "execvp(external/llvm_toolchain/bin/llvm-ar, 0x13748f0)": No such file or directory
```

The file mentioned exists for me; I suspect something changed with the sandboxing in the new version of Bazel.

Same BUILD files work fine on older versions of Bazel.

**Comment by siddharthab** [comment]
Thanks for the report. I will try to get to it over this weekend.

**Comment by luxe** [comment]
more specifically, something like this fails:  
```
/home/laptop/.cache/bazel/_bazel_laptop/install/a4696acfbd71b79376c811717f94d1ac/_embedded_binaries/linux-sandbox -t 15 -w /home/laptop/.cache/bazel/_bazel_laptop/9e74040f84b92184f3149fef1e79ff7d/sandbox/linux-sandbox/123/execroot/__main__ -w /tmp -w /dev/shm -D -- external/llvm_toolchain/bin/llvm-ar @bazel-out/host/bin/external/boost/libchrono.a-2.params
```

The external path(external/llvm_toolchain/bin/llvm-ar) is no longer there.  Somehow no longer copied into the sandbox.

**Comment by luxe** [comment]
I think we need to add an ar action in `cc_toolchain_config.bzl`
https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html#ar-actions

**Comment by luxe** [comment]
It seems the execroot occasionally doesn't include the `external/` folder where the llvm tools are (clang and ar), but I've seen it show up for things like clang++

temporary hack: `--strategy=CppCompile=standalone --strategy=CppLink=standalone`.
It leaves the sandbox which is undesirable.

**Comment by luxe** [comment]
This ticket explains the issue well.  
https://github.com/bazelbuild/bazel/issues/8531

I've solved the problem with:  
`--incompatible_use_specific_tool_files=false`

To fix this, we could probably change `native.cc_toolchain` to use `ar_files`
https://github.com/grailbio/bazel-toolchain/blob/f2d0aeca399e70297414341d228c7be460b4d6a0/toolchain/internal/configure.bzl#L126

But at the same time, the docs say `ar_files` is currently not used.
https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library

**Comment by siddharthab** [comment]
Thank you for the investigation. Your help made this an easy task for me.
