### ISSUE TITLE
Distro detection sometimes produces non-existing download URLs

### ISSUE THREAD

**Issue by hperl** [grailbio/bazel-toolchain#3]
The Linux distro detection is more subtle than the current code in `toolchain/llvm_release_name.py` suggests.

 * Some archives (like debian-8) are present in 6.0.0 but not in 6.0.1
 * For some distributions (like ubuntu) only some releases (14.04 and 16.04) are present, so just formatting the version into the URL will result in non-existing URLs in cases where the release is not 14.04 or 16.04

However, the build for ubuntu 16.04 runs fine on newer versions of ubuntu.

My suggested fix is as follows:

 * The script should keep a table of known valid distro URLs for each supported release
 * The matching logic should match from distro name to valid URL

Docker can be used to check which version works for which release build in order to create a working mapping.

**Comment by siddharthab** [comment]
We already have a table of valid URLs for release versions 6.0.0 and 6.0.1.

As for different versions of linux distros, we can build a map of linux versions to LLVM distributions, but I don't feel comfortable maintaining such a map or logic. I will let this part be community driven.

What I can do right now is provide a way to skip the auto detection and manually provide an LLVM distribution name. That should also help in docker based sandbox execution and remote executions.

I can also set up a script which can run the tests in a list of docker images to keep a list of OS distributions that have been officially tested.

**Comment by siddharthab** [comment]
Oops! Sorry for the spam. I did not realize all my travis testing would show up here. Should have forked the repo. Anyway.

So, I have added a script that tests ubuntu 16.04. I think this makes a good setup for community contributions. People can fix the auto detection, like you did for arch, and include a test script. If they don't want to go through this, then they can manually specify the distribution attribute.

**Comment by siddharthab** [comment]
All done now. No more commits, I promise. :smile:

**Comment by siddharthab** [comment]
74988d49dcb8c30c4bcb21cadbc24a4433138b49 should also improve OS detection in the lines of what you wanted. I also put in a test for archlinux.

**Comment by hperl** [comment]
These commits don't yet completely fix the issue for Debian-8 with LLVM 6.0.1. All tests are only run against LLVM 6.0.0. And while there exists a
http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-debian8.tar.xz, there is no http://releases.llvm.org/6.0.0/clang+llvm-6.0.1-x86_64-linux-gnu-debian8.tar.xz.

However, the detection script does not know how to handle 6.0.0 and 6.0.1 differently. And the tests only check 6.0.0.

Would you like me to open up new issues? I know commenting on closed issues is bad style ;).

Thanks for your work by the way!

**Comment by siddharthab** [comment]
It will be difficult to maintain a detection script for every os distro and llvm version. The script will always be best effort. Supporting and testing patch versions is somewhat out of scope.

My expectation here is that if someone needs a specific pairing, they can send a PR. Otherwise, they can always manually specify which pre-built binaries they want as an attribute.

You can open a separate issue but there is a good chance that I will consider it as out of scope for this project. We can keep an umbrella issue always open for others to easily find.
