### ISSUE TITLE
Question: how to make this toolchain default?

### ISSUE THREAD

**Issue by Monnoroch** [grailbio/bazel-toolchain#35]
I would like to build my C++ code as hermetically as possible. E.g. on a host (or in a container) without a C compiler installed (a.k.a. `unset CC`). From what I can see, this project makes it possible. When I use this toolchain I can see that Bazel uses the downloaded compiler to build C++ code.

However when I actually execute `unset CC` and perform a clean build things break:

```
ERROR: Traceback (most recent call last):
	File "/X/external/bazel_tools/tools/cpp/cc_configure.bzl", line 125
		configure_unix_toolchain(<3 more arguments>)
	File "/X/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 333, in configure_unix_toolchain
		_find_generic(repository_ctx, <3 more arguments>)
	File "/X/external/bazel_tools/tools/cpp/unix_cc_configure.bzl", line 304, in _find_generic
		auto_configure_fail(msg)
	File "/X/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, in auto_configure_fail
		fail(<1 more arguments>)

Auto-Configuration Error: Cannot find gcc or CC; either correct your path or set the CC environment variable
```

I'm not an expert in the "toolchains" part of Bazel but from what I understand using `--extra_toolchains=@llvm_toolchain//:cc-toolchain-linux` literally adds an EXTRA toolchain and the default autoconfigured one is still being configured. Is there a way to prevent Bazel from autoconfiguring the default toolchain?

I noticed this line in the README:

> For making changes to default settings for these toolchains, edit the cc_toolchain_config template. See tutorial.

I feel like it's something related, but I'm having a hard time mapping the suggested tutorial to what I'm trying to achieve in practice. Any chance you could help with that and create an example for this repo in the process?

**Comment by siddharthab** [comment]
Hi!

Thanks for asking a good question.

So that looks like a bug or incorrect design in bazel, which I am hoping they will fix eventually.

In the meantime, you can use the `--crosstool_top` option which will work correctly and you should be able to build your binary without using gcc.

However, we still depend on /usr/bin/ld and /usr/bin/ar in the toolchain, so it is not completely hermetic. I will have to see how to make the LLVM toolchain work without picking up these binaries from the system. If you know how to get `ld` and `ar` from the LLVM distribution itself, I can change the way the toolchain looks for it. Last I looked into it (llvm 6.0.0), I could not find any.

**Comment by siddharthab** [comment]
Also, you can not use glibc if you want hermeticity because llvm will then look for an underlying gcc installation to provide glibc.

**Comment by Monnoroch** [comment]
Thanks for a swift reply! Yes, I read the code and saw host dependencies. That's why I said "as possible".

In addition to what you said, I've tested the 9.0.0 and got this error:

```
external/llvm_toolchain/bin/ld.lld: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory
```

So there's at least one more dependency. I'll follow up once I manage to make the toolchain work.

**Comment by siddharthab** [comment]
Closing for now. Will reopen if any action items come up for this project.

**Comment by Monnoroch** [comment]
How about a `repository_rule`s for the linker and libxml2?
