### ISSUE TITLE
Support for toolchains checked out in a repo tree

### ISSUE THREAD

**Issue by kruton** [grailbio/bazel-toolchain#40]
In some environments, toolchains are distributed as part of a git repository checkout (i.e., via submodules) to avoid downloading the toolchain every time on a CI environment and tracking of what tree state made a binary for reproducability. Support for these environments would be nice.

A typical layout might look like Android's usage of this pattern:
[`prebuilts/clang/host/linux-x86`](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/) is checked out in the tree and you'd point to [`prebuilts/clang/host/linux-x86/clang-r377782c`](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/clang-r377782c/) for all the binaries.

An example configuration might look like:
```
# cloned from https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86
new_local_repository(
    name = "prebuilts_clang_host_linux_x86",
    path = "prebuilts/clang/host/linux-x86",
    build_file_content = """
       filegroup(name="clang-r377782c", srcs=glob(["clang-r377782c/**"]))
    """,
)

llvm_toolchain(
    name = "llvm_toolchain",
    toolchain_root = {
        "linux": "@prebuilts_clang_host_linux_x86//:clang-r377782c",
        "darwin": "@prebuilts_clang_host_darwin_x86//:clang-r377782c",
    },
)
```

**Comment by siddharthab** [comment]
It's a good suggestion. Will get it in when I work on the next set of changes.

**Comment by jsharpe** [comment]
Looks like https://github.com/samolisov/bazel-llvm-bridge can do this

**Comment by siddharthab** [comment]
Thanks for bringing the project to my attention.

**Comment by siddharthab** [comment]
This seems to be a potential blocker: bazel#7746. Will see if I can work around it.
