### ISSUE TITLE
sysroot thoughts?

### ISSUE THREAD

**Issue by asa** [grailbio/bazel-toolchain#5]
Any pointers on building up a sysroot to go with this so we can have this be fully hermetic?

**Comment by siddharthab** [comment]
Yes, definitely. Should also enable cross compilation from Linux to Mac and vice versa. I will get to it sometime by the end of this year. The main problem has been getting a pre-made sysroot bundle for Ubuntu or some other Linux distro. I have been lazy about making my own.

**Comment by ixdy** [comment]
@siddharthab have you had a chance to look into this more? I'd love to have sysroots for other architectures under linux too, though it seems like it might be quite the undertaking.

**Comment by siddharthab** [comment]
I have been lazy about preparing/finding a default sysroot, but now I think I should just give users a parameter and they can bring their own sysroot. WDYT?

**Comment by ixdy** [comment]
That would be a start. Is there a best practice on how to build/host sysroots?

**Comment by siddharthab** [comment]
I could not find anything easily last year. I will look again.

**Comment by siddharthab** [comment]
I think 20773e513f2da981d9625b79c5ce76b3e7355423 is the best we can do here.

I have updated the README on some ideas for creating a sysroot. The WORKSPACE file for this project also defines a sysroot, and is used in the unit tests here.

Closing this issue.
