### ISSUE TITLE
Archlinux and LLVM 10.0.0

### ISSUE THREAD

**Issue by Kernald** [grailbio/bazel-toolchain#53]
Trying to use LLVM 10.0.0 on Archlinux with the latest version of this toolchain (0.5.6) raises this error:

```
Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
```

For some reason, [here](https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/tools/llvm_release_name.py#L77) Archlinux is assumed to be a Ubuntu 16.04 equivalent indeed. It worked fine with LLVM 8.0.0 and 9.0.0, but LLVM doesn't provide prebuilt archives for Ubuntu 16.04 on x86_64 anymore for LLVM 10.0.0 (list [here](https://github.com/llvm/llvm-project/releases/tag/llvmorg-10.0.0)).

**Comment by siddharthab** [comment]
Hi! Thanks for the report. Will you be able to send a PR with the correct logic?

**Comment by Kernald** [comment]
I'm not sure why Archlinux is assumed  to be a Ubuntu 16.04 equivalent in the first place - is there a strong reason not to go with Ubuntu 18.04? Given the rolling release nature of Archlinux, sticking to the most recent target should be fine, I guess? Happy to send a PR moving it to that section if that sounds good.

**Comment by siddharthab** [comment]
I think it's because when the logic was originally written, 16.04 was the most current.

https://github.com/grailbio/bazel-toolchain/commit/c9b6393fe6eef648c127246614b2afcfc7a6759e

**Comment by Kernald** [comment]
Makes sense, thanks! I'm just finishing some tests to verify that the 18.04 archive indeed works fine, and I'll open a PR if it's all good.
