### ISSUE TITLE
No interface for linking with gnu standard library instead of clang

### ISSUE THREAD

**Issue by alisafari1998** [grailbio/bazel-toolchain#63]
As far as I know in `toolchain/cc_toolchain_config.bzl.tpl` static linkage to `libc++` is hard coded also only way of removing `-stdlib=libc++` is to remove `default_compile_flags` from features of cc_library.

Is there any plan to support gnu standard library?!

**Comment by siddharthab** [comment]
I believe this can be tackled as part of adding more configurability to the toolchain.

**Comment by kshcherban** [comment]
Same issue when trying to link with pytorch. 
```
ld.lld: error: undefined symbol: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
          >>> referenced by torch_api.cpp
          >>>               torch_api.o:(c10::Type::createWithContained(std::__1::vector<std::__1::shared_ptr<c10::Type>, std::__1::allocator<std::__1::shared_ptr<c10::Type> > >) const) in archive bazel-out/k8-opt/bin/external/raze__torch_sys__0_5_0/libtch.a
```

Looking forward for this feature to be implemented 🙌🏻
