### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by jsharpe** [grailbio/bazel-toolchain#68]
Would it be possible to get a release tagged? Only releases provide a download tarball that is guaranteed to have a stable sha256 so its useful if we can have up to date releases cut.

**Comment by siddharthab** [comment]
I will do it now.

**Comment by siddharthab** [comment]
[0.5.7](https://github.com/grailbio/bazel-toolchain/releases/tag/0.5.7) pushed.

**Comment by jsharpe** [comment]
Thanks
