### ISSUE TITLE
where is clang+llvm-7.0.0-x86_64-linux-gnu-debian8.tar.xz?

### ISSUE THREAD

**Issue by luxe** [grailbio/bazel-toolchain#8]
This isn't really a problem with the repository, but I wonder why clang has:  
https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-debian8.tar.xz
but not:  
https://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-debian8.tar.xz

Why did they stop making debian8 binaries for 7.0.0?  

https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/configure.bzl#L53 is deriving a package name for me in 7.0.0 that doesn't exist (clang+llvm-7.0.0-x86_64-linux-gnu-debian8.tar.xz).

**Comment by ixdy** [comment]
I'd guess it's because debian8 has reached end-of-life. debian9 is the current stable release.

**Comment by siddharthab** [comment]
Hello @luxe 

I think they have substantially reduced the number of operating systems for which they release pre-compiled binaries. Debian seems to have dropped out of the supported list.

You have two options:
1. Compile your own LLVM distribution for debian8 and manually provide as an attribute to the `llvm_toolchain` repository rule.
2. Try using one of the pre-compiled distributions for ubuntu. It may work without problems. We already do this for mint linux. If this works for you, please feel free to send a PR to change the detection logic.

I will keep this issue open for some time.

**Comment by siddharthab** [comment]
Closing because I could not think of any other ideas here. I do not want this project to host its own pre-compiled LLVM distributions.

**Comment by DavidS** [comment]
Debian has a completely fine llvm 6, 7 and 8 packages.
