### ISSUE TITLE
Debian 11 Support in LLVM toolchain

### ISSUE THREAD

**Issue by JoshVarga** [grailbio/bazel-toolchain#87]
Debian 11 (which was officially released August 14 2021) is not explicitly supported currently, but seems that using the following would work correctly.

os_name = "linux-gnu-ubuntu-18.04"

The check for OS version is here:
https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/tools/llvm_release_name.py#L95-L100

Would you accept a pull request for this change?

**Comment by siddharthab** [comment]
This was picked up in f54297f4 when I was fixing the container test failures. The container test for debian now uses Debian 11. Thanks.
